name: Scheduled Update

on:
  schedule:
    - cron: "0 0 * * *" # This runs the job every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yq
          sudo apt-get install sqlite3

      - name: Update source data
        run: cd ourairports-data && git pull origin master

      - name: Run compile script
        run: ./compile.sh

      - name: Check for changes
        id: check_changes
        run: |
          git fetch
          if git diff --exit-code navdata.db; then
            echo "No changes detected" > no_changes
          fi

      - name: Stop job if no changes
        if: steps.check_changes.outputs.no_changes
        run: echo "No changes to commit"

      - name: Update version.yml
        run: |
          run_number=$(echo ${{github.run_id}})
          yq eval ".versionId = \"$run_number\"" -i version.yml
          today=$(date +'%Y-%m-%d')
          yq eval ".lastUpdated = \"$today\"" -i version.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
